[package]
name = "evcxr_input"
version = "1.0.0"
license = "Apache-2.0"
description = "Support for reading input from the user in Evcxr"
repository = "https://github.com/google/evcxr"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
]
edition = "2018"

[dependencies]
